services:
  frontend:
    build:
      context: .
      dockerfile: deploy/docker/frontend.Dockerfile
      args:
        - NEXT_PUBLIC_OPENWEATHER_API_KEY=${NEXT_PUBLIC_OPENWEATHER_API_KEY}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_OPENWEATHER_API_KEY=${NEXT_PUBLIC_OPENWEATHER_API_KEY}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: deploy/docker/backend.Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
        - CORS_ORIGINS=${CORS_ORIGINS}
        - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
        - BASE_URL=${BASE_URL}
        - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
        - RATE_LIMIT_MAX=${RATE_LIMIT_MAX}
        - CACHE_TTL=${CACHE_TTL}
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - BASE_URL=${BASE_URL}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX}
      - CACHE_TTL=${CACHE_TTL}