# docker-compose.yml
services:
  frontend:
    build:
      context: .
      dockerfile: deploy/docker/frontend.Dockerfile
      args:
        - NEXT_PUBLIC_OPENWEATHER_API_KEY=${NEXT_PUBLIC_OPENWEATHER_API_KEY}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-https://k8s-weatherly-5842770101-1506936625.us-east-1.elb.amazonaws.com/api/v1/weather}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_OPENWEATHER_API_KEY=${NEXT_PUBLIC_OPENWEATHER_API_KEY}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-https://k8s-weatherly-5842770101-1506936625.us-east-1.elb.amazonaws.com/api/v1/weather}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: deploy/docker/backend.Dockerfile
      args:
        - NODE_ENV=production
        - PORT=5000
        - CORS_ORIGINS=*
        - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
        - BASE_URL=${BASE_URL}
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CORS_ORIGINS=*
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - BASE_URL=${BASE_URL}
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=100
      - CACHE_TTL=1800000