# 2. Updated ConfigMap (configmap-and-secret.yaml)
apiVersion: v1
kind: ConfigMap
metadata:
  name: weatherly-config
data:
  NODE_ENV: "production"
  CORS_ORIGINS: "*"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX: "100"
  CACHE_TTL: "1800000"
  BASE_URL: "https://api.openweathermap.org/data/2.5"
  NEXT_PUBLIC_API_BASE_URL: "https://k8s-weatherly-5842770101-1506936625.us-east-1.elb.amazonaws.com/api/v1/weather"
---
# 2. Updated Secret
apiVersion: v1
kind: Secret
metadata:
  name: weatherly-secret
type: Opaque
stringData:
  OPENWEATHER_API_KEY: ""
  NEXT_PUBLIC_OPENWEATHER_API_KEY: ""
  NEXT_PUBLIC_BASE_URL: "https://k8s-weatherly-5842770101-1506936625.us-east-1.elb.amazonaws.com"